<?xml version="1.0" encoding="utf-8"?><Database Name="YunShanOA" Class="YunShanOADataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=.\SQLEXPRESS;Initial Catalog=YunShanOA;Integrated Security=True" SettingsObjectName="YunShanOA.DataAccess.Properties.Settings" SettingsPropertyName="YunShanOAConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Activities" Member="Activities">
    <Type Name="Activities">
      <Column Name="ActID" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="ACTTempID" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="ActName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="WFID" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="Owners" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="LastUpdateUser" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="LastUpdateTime" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Status" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.WorkflowTemplates" Member="WorkflowTemplates">
    <Type Name="WorkflowTemplates">
      <Column Name="WFTID" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="WFTName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.ArchiveMeeting" Member="ArchiveMeeting">
    <Type Name="ArchiveMeeting">
      <Column Name="ArchiveMeetingID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="MeetingApplyFormID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="FileName" Type="System.String" DbType="NVarChar(1000)" CanBeNull="true" />
      <Column Name="FilePath" Type="System.String" DbType="NVarChar(1000)" CanBeNull="true" />
      <Association Name="MeetingApplyForm_ArchiveMeeting" Member="MeetingApplyForm" ThisKey="MeetingApplyFormID" OtherKey="MeetingApplyFormID" Type="MeetingApplyForm" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.ArchiveUserCarApply" Member="ArchiveUserCarApply">
    <Type Name="ArchiveUserCarApply">
      <Column Name="ArchiveUserCarID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="UseCarApplyFormID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="FileName" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="FilePath" Type="System.String" DbType="NVarChar(200) NOT NULL" CanBeNull="false" />
      <Association Name="UseCarApplyForm_ArchiveUserCarApply" Member="UseCarApplyForm" ThisKey="UseCarApplyFormID" OtherKey="UseCarApplyFormID" Type="UseCarApplyForm" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.aspnet_Applications" Member="aspnet_Applications">
    <Type Name="aspnet_Applications">
      <Column Name="ApplicationName" Type="System.String" DbType="NVarChar(256) NOT NULL" CanBeNull="false" />
      <Column Name="LoweredApplicationName" Type="System.String" DbType="NVarChar(256) NOT NULL" CanBeNull="false" />
      <Column Name="ApplicationId" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Description" Type="System.String" DbType="NVarChar(256)" CanBeNull="true" />
      <Association Name="aspnet_Applications_aspnet_Membership" Member="aspnet_Membership" ThisKey="ApplicationId" OtherKey="ApplicationId" Type="aspnet_Membership" />
      <Association Name="aspnet_Applications_aspnet_Paths" Member="aspnet_Paths" ThisKey="ApplicationId" OtherKey="ApplicationId" Type="aspnet_Paths" />
      <Association Name="aspnet_Applications_aspnet_Roles" Member="aspnet_Roles" ThisKey="ApplicationId" OtherKey="ApplicationId" Type="aspnet_Roles" />
      <Association Name="aspnet_Applications_aspnet_Users" Member="aspnet_Users" ThisKey="ApplicationId" OtherKey="ApplicationId" Type="aspnet_Users" />
    </Type>
  </Table>
  <Table Name="dbo.aspnet_Membership" Member="aspnet_Membership">
    <Type Name="aspnet_Membership">
      <Column Name="ApplicationId" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="UserId" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Password" Type="System.String" DbType="NVarChar(128) NOT NULL" CanBeNull="false" />
      <Column Name="PasswordFormat" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="PasswordSalt" Type="System.String" DbType="NVarChar(128) NOT NULL" CanBeNull="false" />
      <Column Name="MobilePIN" Type="System.String" DbType="NVarChar(16)" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="NVarChar(256)" CanBeNull="true" />
      <Column Name="LoweredEmail" Type="System.String" DbType="NVarChar(256)" CanBeNull="true" />
      <Column Name="PasswordQuestion" Type="System.String" DbType="NVarChar(256)" CanBeNull="true" />
      <Column Name="PasswordAnswer" Type="System.String" DbType="NVarChar(128)" CanBeNull="true" />
      <Column Name="IsApproved" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="IsLockedOut" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="CreateDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="LastLoginDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="LastPasswordChangedDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="LastLockoutDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="FailedPasswordAttemptCount" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="FailedPasswordAttemptWindowStart" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="FailedPasswordAnswerAttemptCount" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="FailedPasswordAnswerAttemptWindowStart" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="Comment" Type="System.String" DbType="NText" CanBeNull="true" UpdateCheck="Never" />
      <Association Name="aspnet_Applications_aspnet_Membership" Member="aspnet_Applications" ThisKey="ApplicationId" OtherKey="ApplicationId" Type="aspnet_Applications" IsForeignKey="true" />
      <Association Name="aspnet_Users_aspnet_Membership" Member="aspnet_Users" ThisKey="UserId" OtherKey="UserId" Type="aspnet_Users" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.aspnet_Paths" Member="aspnet_Paths">
    <Type Name="aspnet_Paths">
      <Column Name="ApplicationId" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="PathId" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Path" Type="System.String" DbType="NVarChar(256) NOT NULL" CanBeNull="false" />
      <Column Name="LoweredPath" Type="System.String" DbType="NVarChar(256) NOT NULL" CanBeNull="false" />
      <Association Name="aspnet_Paths_aspnet_PersonalizationAllUsers" Member="aspnet_PersonalizationAllUsers" ThisKey="PathId" OtherKey="PathId" Type="aspnet_PersonalizationAllUsers" Cardinality="One" />
      <Association Name="aspnet_Paths_aspnet_PersonalizationPerUser" Member="aspnet_PersonalizationPerUser" ThisKey="PathId" OtherKey="PathId" Type="aspnet_PersonalizationPerUser" />
      <Association Name="aspnet_Applications_aspnet_Paths" Member="aspnet_Applications" ThisKey="ApplicationId" OtherKey="ApplicationId" Type="aspnet_Applications" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.aspnet_PersonalizationAllUsers" Member="aspnet_PersonalizationAllUsers">
    <Type Name="aspnet_PersonalizationAllUsers">
      <Column Name="PathId" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="PageSettings" Type="System.Data.Linq.Binary" DbType="Image NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="LastUpdatedDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Association Name="aspnet_Paths_aspnet_PersonalizationAllUsers" Member="aspnet_Paths" ThisKey="PathId" OtherKey="PathId" Type="aspnet_Paths" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.aspnet_PersonalizationPerUser" Member="aspnet_PersonalizationPerUser">
    <Type Name="aspnet_PersonalizationPerUser">
      <Column Name="Id" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="PathId" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="UserId" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="PageSettings" Type="System.Data.Linq.Binary" DbType="Image NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="LastUpdatedDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Association Name="aspnet_Paths_aspnet_PersonalizationPerUser" Member="aspnet_Paths" ThisKey="PathId" OtherKey="PathId" Type="aspnet_Paths" IsForeignKey="true" />
      <Association Name="aspnet_Users_aspnet_PersonalizationPerUser" Member="aspnet_Users" ThisKey="UserId" OtherKey="UserId" Type="aspnet_Users" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.aspnet_Profile" Member="aspnet_Profile">
    <Type Name="aspnet_Profile">
      <Column Name="UserId" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="PropertyNames" Type="System.String" DbType="NText NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="PropertyValuesString" Type="System.String" DbType="NText NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="PropertyValuesBinary" Type="System.Data.Linq.Binary" DbType="Image NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="LastUpdatedDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Association Name="aspnet_Users_aspnet_Profile" Member="aspnet_Users" ThisKey="UserId" OtherKey="UserId" Type="aspnet_Users" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.aspnet_Roles" Member="aspnet_Roles">
    <Type Name="aspnet_Roles">
      <Column Name="ApplicationId" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="RoleId" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="RoleName" Type="System.String" DbType="NVarChar(256) NOT NULL" CanBeNull="false" />
      <Column Name="LoweredRoleName" Type="System.String" DbType="NVarChar(256) NOT NULL" CanBeNull="false" />
      <Column Name="Description" Type="System.String" DbType="NVarChar(256)" CanBeNull="true" />
      <Association Name="aspnet_Roles_aspnet_UsersInRoles" Member="aspnet_UsersInRoles" ThisKey="RoleId" OtherKey="RoleId" Type="aspnet_UsersInRoles" />
      <Association Name="aspnet_Applications_aspnet_Roles" Member="aspnet_Applications" ThisKey="ApplicationId" OtherKey="ApplicationId" Type="aspnet_Applications" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.aspnet_SchemaVersions" Member="aspnet_SchemaVersions">
    <Type Name="aspnet_SchemaVersions">
      <Column Name="Feature" Type="System.String" DbType="NVarChar(128) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="CompatibleSchemaVersion" Type="System.String" DbType="NVarChar(128) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="IsCurrentVersion" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.AspNet_SqlCacheTablesForChangeNotification" Member="AspNet_SqlCacheTablesForChangeNotification">
    <Type Name="AspNet_SqlCacheTablesForChangeNotification">
      <Column Name="tableName" Type="System.String" DbType="NVarChar(450) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="notificationCreated" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="changeId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.aspnet_Users" Member="aspnet_Users">
    <Type Name="aspnet_Users">
      <Column Name="ApplicationId" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="UserId" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="UserName" Type="System.String" DbType="NVarChar(256) NOT NULL" CanBeNull="false" />
      <Column Name="LoweredUserName" Type="System.String" DbType="NVarChar(256) NOT NULL" CanBeNull="false" />
      <Column Name="MobileAlias" Type="System.String" DbType="NVarChar(16)" CanBeNull="true" />
      <Column Name="IsAnonymous" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="LastActivityDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Association Name="aspnet_Users_aspnet_Membership" Member="aspnet_Membership" ThisKey="UserId" OtherKey="UserId" Type="aspnet_Membership" Cardinality="One" />
      <Association Name="aspnet_Users_aspnet_PersonalizationPerUser" Member="aspnet_PersonalizationPerUser" ThisKey="UserId" OtherKey="UserId" Type="aspnet_PersonalizationPerUser" />
      <Association Name="aspnet_Users_aspnet_Profile" Member="aspnet_Profile" ThisKey="UserId" OtherKey="UserId" Type="aspnet_Profile" Cardinality="One" />
      <Association Name="aspnet_Users_aspnet_UsersInRoles" Member="aspnet_UsersInRoles" ThisKey="UserId" OtherKey="UserId" Type="aspnet_UsersInRoles" />
      <Association Name="aspnet_Applications_aspnet_Users" Member="aspnet_Applications" ThisKey="ApplicationId" OtherKey="ApplicationId" Type="aspnet_Applications" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.aspnet_UsersInRoles" Member="aspnet_UsersInRoles">
    <Type Name="aspnet_UsersInRoles">
      <Column Name="UserId" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="RoleId" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Association Name="aspnet_Roles_aspnet_UsersInRoles" Member="aspnet_Roles" ThisKey="RoleId" OtherKey="RoleId" Type="aspnet_Roles" IsForeignKey="true" />
      <Association Name="aspnet_Users_aspnet_UsersInRoles" Member="aspnet_Users" ThisKey="UserId" OtherKey="UserId" Type="aspnet_Users" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.aspnet_WebEvent_Events" Member="aspnet_WebEvent_Events">
    <Type Name="aspnet_WebEvent_Events">
      <Column Name="EventId" Type="System.String" DbType="Char(32) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="EventTimeUtc" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="EventTime" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="EventType" Type="System.String" DbType="NVarChar(256) NOT NULL" CanBeNull="false" />
      <Column Name="EventSequence" Type="System.Decimal" DbType="Decimal(19,0) NOT NULL" CanBeNull="false" />
      <Column Name="EventOccurrence" Type="System.Decimal" DbType="Decimal(19,0) NOT NULL" CanBeNull="false" />
      <Column Name="EventCode" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="EventDetailCode" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Message" Type="System.String" DbType="NVarChar(1024)" CanBeNull="true" />
      <Column Name="ApplicationPath" Type="System.String" DbType="NVarChar(256)" CanBeNull="true" />
      <Column Name="ApplicationVirtualPath" Type="System.String" DbType="NVarChar(256)" CanBeNull="true" />
      <Column Name="MachineName" Type="System.String" DbType="NVarChar(256) NOT NULL" CanBeNull="false" />
      <Column Name="RequestUrl" Type="System.String" DbType="NVarChar(1024)" CanBeNull="true" />
      <Column Name="ExceptionType" Type="System.String" DbType="NVarChar(256)" CanBeNull="true" />
      <Column Name="Details" Type="System.String" DbType="NText" CanBeNull="true" UpdateCheck="Never" />
    </Type>
  </Table>
  <Table Name="dbo.Automobile" Member="Automobile">
    <Type Name="Automobile">
      <Column Name="AutomobileID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Driver" Type="System.String" DbType="NVarChar(2000) NOT NULL" CanBeNull="false" />
      <Column Name="AutomobileLicensePlace" Type="System.String" DbType="NVarChar(2000) NOT NULL" CanBeNull="false" />
      <Column Name="AutomobileType" Type="System.String" DbType="NVarChar(500) NOT NULL" CanBeNull="false" />
      <Column Name="AutomobileSeatings" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="AutomobileCapacity" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="AutomobileStatus" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Comments" Type="System.String" DbType="NVarChar(1000) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.AutomobileUse" Member="AutomobileUse">
    <Type Name="AutomobileUse">
      <Column Name="AutomobileUseID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="AutomobileUseFormID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="AutomobileID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="AutomobileUseForm_AutomobileUse" Member="AutomobileUseForm" ThisKey="AutomobileUseFormID" OtherKey="AutomobileUserFormID" Type="AutomobileUseForm" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.AutomobileUseForm" Member="AutomobileUseForm">
    <Type Name="AutomobileUseForm">
      <Column Name="AutomobileUserFormID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="BeginAddress" Type="System.String" DbType="NVarChar(1000) NOT NULL" CanBeNull="false" />
      <Column Name="EndAddress" Type="System.String" DbType="NVarChar(1000) NOT NULL" CanBeNull="false" />
      <Column Name="BeginTime" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="EndTime" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="UserName" Type="System.String" DbType="NVarChar(400) NOT NULL" CanBeNull="false" />
      <Column Name="Status" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Purpose" Type="System.String" DbType="NVarChar(1000) NOT NULL" CanBeNull="false" />
      <Association Name="AutomobileUseForm_AutomobileUse" Member="AutomobileUse" ThisKey="AutomobileUserFormID" OtherKey="AutomobileUseFormID" Type="AutomobileUse" />
    </Type>
  </Table>
  <Table Name="dbo.AutomobileUser" Member="AutomobileUser">
    <Type Name="AutomobileUser">
      <Column Name="AutomobileUserID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="UserName" Type="System.String" DbType="NVarChar(2000) NOT NULL" CanBeNull="false" />
      <Column Name="AutomobileUseFormID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.Car" Member="Car">
    <Type Name="Car">
      <Column Name="CarId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="UseCarTypeID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="DriverEmail" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Driver" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="LicenseNumber" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="ModelNumber" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="SeatingNumber" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Status" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="LoadCapacity" Type="System.String" DbType="NVarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="Comment" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Association Name="UseCarType_Car" Member="UseCarType" ThisKey="UseCarTypeID" OtherKey="UseCarTypeID" Type="UseCarType" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.DocumentAndWFT" Member="DocumentAndWFT">
    <Type Name="DocumentAndWFT">
      <Column Name="WFTID" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="DocumentTemplateID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="WFTDescription" Type="System.String" DbType="NVarChar(400)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.DocumentProcessAct" Member="DocumentProcessAct">
    <Type Name="DocumentProcessAct">
      <Column Name="NodeGuid" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="nodeName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="nodeRoles" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.DocumentTemplate" Member="DocumentTemplate">
    <Type Name="DocumentTemplate">
      <Column Name="DocumentTemplateID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="DocumentTemplateName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="DocumentTemplateDescription" Type="System.String" DbType="NVarChar(400)" CanBeNull="true" />
      <Column Name="DocumentTemplatePath" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.[Log]" Member="Log">
    <Type Name="Log">
      <Column Name="LogID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="UserName" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="LogType" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="LogContent" Type="System.String" DbType="VarChar(1000)" CanBeNull="true" />
      <Column Name="LogTime" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.MeetingAndEquipment" Member="MeetingAndEquipment">
    <Type Name="MeetingAndEquipment">
      <Column Name="MeetingAndEquipmentID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="MeetingApplyFormID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="MeetingEquipmentID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="MeetingEquipmentCount" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="MeetingEquipment_MeetingAndEquipment" Member="MeetingEquipment" ThisKey="MeetingEquipmentID" OtherKey="MeetingEquipmentID" Type="MeetingEquipment" IsForeignKey="true" />
      <Association Name="MeetingApplyForm_MeetingAndEquipment" Member="MeetingApplyForm" ThisKey="MeetingApplyFormID" OtherKey="MeetingApplyFormID" Type="MeetingApplyForm" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.MeetingAndRoom" Member="MeetingAndRoom">
    <Type Name="MeetingAndRoom">
      <Column Name="MeetingAndRoomID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="MeetingApplyFormID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="MeetingRoomID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Status" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="MeetingRoom_MeetingAndRoom" Member="MeetingRoom" ThisKey="MeetingRoomID" OtherKey="MeetingRoomID" Type="MeetingRoom" IsForeignKey="true" />
      <Association Name="MeetingApplyForm_MeetingAndRoom" Member="MeetingApplyForm" ThisKey="MeetingApplyFormID" OtherKey="MeetingApplyFormID" Type="MeetingApplyForm" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.MeetingAndUser" Member="MeetingAndUser">
    <Type Name="MeetingAndUser">
      <Column Name="MeetingAndUserID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="UserName" Type="System.String" DbType="NVarChar(2000) NOT NULL" CanBeNull="false" />
      <Column Name="MeetingApplyFormID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.MeetingEquipment" Member="MeetingEquipment">
    <Type Name="MeetingEquipment">
      <Column Name="MeetingEquipmentID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="EquipmentName" Type="System.String" DbType="NVarChar(14) NOT NULL" CanBeNull="false" />
      <Column Name="EquipmentDescription" Type="System.String" DbType="NVarChar(400)" CanBeNull="true" />
      <Column Name="Status" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="MeetingEquipmentCount" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="MeetingEquipmentFreeCount" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Comments" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Association Name="MeetingEquipment_MeetingAndEquipment" Member="MeetingAndEquipment" ThisKey="MeetingEquipmentID" OtherKey="MeetingEquipmentID" Type="MeetingAndEquipment" />
    </Type>
  </Table>
  <Table Name="dbo.MeetingParticipationMember" Member="MeetingParticipationMember">
    <Type Name="MeetingParticipationMember">
      <Column Name="MeetingApplyFormID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="EmployeeNo" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MePartiMemberName" Type="System.String" DbType="NVarChar(14) NOT NULL" CanBeNull="false" />
      <Association Name="MeetingApplyForm_MeetingParticipationMember" Member="MeetingApplyForm" ThisKey="MeetingApplyFormID" OtherKey="MeetingApplyFormID" Type="MeetingApplyForm" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.MeetingRoom" Member="MeetingRoom">
    <Type Name="MeetingRoom">
      <Column Name="MeetingRoomID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="MeetingRoomName" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="MeetingRoomCapacity" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="MeetingRoomStatus" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="MeetingTypeID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="MeetingRoom_MeetingAndRoom" Member="MeetingAndRoom" ThisKey="MeetingRoomID" OtherKey="MeetingRoomID" Type="MeetingAndRoom" />
      <Association Name="MeetingType_MeetingRoom" Member="MeetingType" ThisKey="MeetingTypeID" OtherKey="MeetingTypeID" Type="MeetingType" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.MeetingType" Member="MeetingType">
    <Type Name="MeetingType">
      <Column Name="MeetingTypeID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="MeetingTypeName" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="MeetingTypeDescription" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Association Name="MeetingType_MeetingRoom" Member="MeetingRoom" ThisKey="MeetingTypeID" OtherKey="MeetingTypeID" Type="MeetingRoom" />
      <Association Name="MeetingType_MeetingApplyForm" Member="MeetingApplyForm" ThisKey="MeetingTypeID" OtherKey="MeetingTypeID" Type="MeetingApplyForm" />
    </Type>
  </Table>
  <Table Name="dbo.MegApplyForm" Member="MegApplyForm">
    <Type Name="MegApplyForm">
      <Column Name="CarApplyFormID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="CarTypeID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="begintDestination" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="EndtDestination" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="BeginTime" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="EndTime" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="WFID" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.ReviewAutoApply" Member="ReviewAutoApply">
    <Type Name="ReviewAutoApply">
      <Column Name="RiviewAutoApplyID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="AutomobileUseFormID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ReviewUserName" Type="System.String" DbType="NVarChar(500) NOT NULL" CanBeNull="false" />
      <Column Name="Agree" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.ReviewMeetingApply" Member="ReviewMeetingApply">
    <Type Name="ReviewMeetingApply">
      <Column Name="ReviewMeetingApplyID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="MeetingApplyFormID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ReviewUserName" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="Agree" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="MeetingApplyForm_ReviewMeetingApply" Member="MeetingApplyForm" ThisKey="MeetingApplyFormID" OtherKey="MeetingApplyFormID" Type="MeetingApplyForm" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.ReviewUseCarApply" Member="ReviewUseCarApply">
    <Type Name="ReviewUseCarApply">
      <Column Name="ReviewUseCarApplyID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="UseCarApplyFormID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ReviewUserName" Type="System.String" DbType="NVarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="Agree" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="UseCarApplyForm_ReviewUseCarApply" Member="UseCarApplyForm" ThisKey="UseCarApplyFormID" OtherKey="UseCarApplyFormID" Type="UseCarApplyForm" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.UseCarAndUser" Member="UseCarAndUser">
    <Type Name="UseCarAndUser">
      <Column Name="UseCarUserId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="UseCarApplyFormID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="Email" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Association Name="UseCarApplyForm_UseCarAndUser" Member="UseCarApplyForm" ThisKey="UseCarApplyFormID" OtherKey="UseCarApplyFormID" Type="UseCarApplyForm" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.UseCarApplyForm" Member="UseCarApplyForm">
    <Type Name="UseCarApplyForm">
      <Column Name="UseCarApplyFormID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ApplyUserName" Type="System.String" DbType="NVarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="UseCarTypeID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="BeginTime" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="EndTime" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="StartDestination" Type="System.String" DbType="NVarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="EndDestination" Type="System.String" DbType="NVarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="ApplyStatus" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="WFID" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="ApplyReason" Type="System.String" DbType="NVarChar(500) NOT NULL" CanBeNull="false" />
      <Column Name="Comment" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Association Name="UseCarApplyForm_ArchiveUserCarApply" Member="ArchiveUserCarApply" ThisKey="UseCarApplyFormID" OtherKey="UseCarApplyFormID" Type="ArchiveUserCarApply" />
      <Association Name="UseCarApplyForm_ReviewUseCarApply" Member="ReviewUseCarApply" ThisKey="UseCarApplyFormID" OtherKey="UseCarApplyFormID" Type="ReviewUseCarApply" />
      <Association Name="UseCarApplyForm_UseCarAndUser" Member="UseCarAndUser" ThisKey="UseCarApplyFormID" OtherKey="UseCarApplyFormID" Type="UseCarAndUser" />
      <Association Name="UseCarType_UseCarApplyForm" Member="UseCarType" ThisKey="UseCarTypeID" OtherKey="UseCarTypeID" Type="UseCarType" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.UseCarType" Member="UseCarType">
    <Type Name="UseCarType">
      <Column Name="UseCarTypeID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="UseCarTypeName" Type="System.String" DbType="NVarChar(20) NOT NULL" CanBeNull="false" />
      <Association Name="UseCarType_Car" Member="Car" ThisKey="UseCarTypeID" OtherKey="UseCarTypeID" Type="Car" />
      <Association Name="UseCarType_UseCarApplyForm" Member="UseCarApplyForm" ThisKey="UseCarTypeID" OtherKey="UseCarTypeID" Type="UseCarApplyForm" />
    </Type>
  </Table>
  <Table Name="dbo.WFT_Acts" Member="WFT_Acts">
    <Type Name="WFT_Acts">
      <Column Name="FromAct" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="ToAct" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.WFTActivities" Member="WFTActivities">
    <Type Name="WFTActivities">
      <Column Name="ActID" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="ActName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="WFTID" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="Owners" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.WorkFlow_Acts" Member="WorkFlow_Acts">
    <Type Name="WorkFlow_Acts">
      <Column Name="FromAct" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="ToAct" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.Workflows" Member="Workflows">
    <Type Name="Workflows">
      <Column Name="WFID" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="WFTID" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="WFName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Status" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="Workflows_MeetingApplyForm" Member="MeetingApplyForm" ThisKey="WFID" OtherKey="WFID" Type="MeetingApplyForm" />
    </Type>
  </Table>
  <Table Name="dbo.MeetingApplyForm" Member="MeetingApplyForm">
    <Type Name="MeetingApplyForm">
      <Column Name="MeetingApplyFormID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ApplyUserName" Type="System.String" DbType="NVarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="MeetingTypeID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="MeetingTopic" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="MeetingIntroduction" Type="System.String" DbType="NVarChar(2000) NOT NULL" CanBeNull="false" />
      <Column Name="BeginTime" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="EndTime" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="MeetingStatus" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="WFID" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="Comments" Type="System.String" DbType="NVarChar(2000) NOT NULL" CanBeNull="false" />
      <Association Name="MeetingApplyForm_ArchiveMeeting" Member="ArchiveMeeting" ThisKey="MeetingApplyFormID" OtherKey="MeetingApplyFormID" Type="ArchiveMeeting" />
      <Association Name="MeetingApplyForm_MeetingAndEquipment" Member="MeetingAndEquipment" ThisKey="MeetingApplyFormID" OtherKey="MeetingApplyFormID" Type="MeetingAndEquipment" />
      <Association Name="MeetingApplyForm_MeetingAndRoom" Member="MeetingAndRoom" ThisKey="MeetingApplyFormID" OtherKey="MeetingApplyFormID" Type="MeetingAndRoom" />
      <Association Name="MeetingApplyForm_MeetingParticipationMember" Member="MeetingParticipationMember" ThisKey="MeetingApplyFormID" OtherKey="MeetingApplyFormID" Type="MeetingParticipationMember" />
      <Association Name="MeetingApplyForm_ReviewMeetingApply" Member="ReviewMeetingApply" ThisKey="MeetingApplyFormID" OtherKey="MeetingApplyFormID" Type="ReviewMeetingApply" />
      <Association Name="MeetingType_MeetingApplyForm" Member="MeetingType" ThisKey="MeetingTypeID" OtherKey="MeetingTypeID" Type="MeetingType" IsForeignKey="true" />
      <Association Name="Workflows_MeetingApplyForm" Member="Workflows" ThisKey="WFID" OtherKey="WFID" Type="Workflows" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Document" Member="Document">
    <Type Name="Document">
      <Column Name="DocumentID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="DocumentName" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Status" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="DocumentPath" Type="System.String" DbType="NVarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="WFID" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="DocumentAuthor" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
</Database>